### ISSUE TITLE
Rename and use a single .yml file

### ISSUE THREAD

**Issue by hectorj2f** [ClusterHQ/flocker-vnx-driver#1]
I saw you're using two `.yml` files which are similar to each other. Shouldn't it be enough to have one specific for the driver, that uses the generic name `agent.yml` ?

thanks ! ping @myechuri 

Output during the installation of the driver: `python setup.py install`

```
creating /etc/flocker
copying example_vnx_agent.yml -> /etc/flocker/
copying config.yml -> /etc/flocker/
```

**Comment by wallrj** [comment]
Thanks @hectorj2f 

I agree. I updated the driver tests to read agent.yml style structure and deleted config.yml. Seems to work.
